### ISSUE TITLE
Wish: start terminal when Xorg starts

### ISSUE THREAD

**Issue by pavelmachek** [maemo-leste/bugtracker#108]
Currently, terminal is pretty much the only usable application, so likely everyone needs one. Starting one by default would be nice.

**Comment by MerlijnWajer** [comment]
@freemangordon @parazyd - I assume we can just add this to some of the xsession files?

**Comment by freemangordon** [comment]
we'd rather create some leste-devel package that does all sort of hacks needed temporarily.

**Comment by dderby** [comment]
We also have the rootfs-overlay for temporary hacks.

**Comment by android-808** [comment]
A leste-devel package is similar to what I suggested the other week.  rootfs-overlay is ok for now but looking forward, I would expect the downloadable images for all platforms/VMs to be a production image, if that's the right term.  As a dev it would be good for all platforms to be able to pull a VM or firmware image that is completely stock to test packages or upgrade scenarios.

Although the overall point of this issue is related to the current state of Leste, introducing temporary hacks that aren't managed by the package manager could lead to issues further down the line when a dev is using an image with one of these hacks left in that hasn't been removed or replaced.

**Comment by pavelmachek** [comment]
I believe doing additional work now with overlays / developer vs. user
options etc is stupid and contraproductive.

Keep it simple. Do the right thing. We don't have real users now, and
we won't have them for few years.

Even real users can simply close the terminal window they don't need...
-- 
(english) http://www.livejournal.com/~pavelmachek
(cesky, pictures) http://atrey.karlin.mff.cuni.cz/~pavel/picture/horses/blog.html

**Comment by dderby** [comment]
By the way, a terminal can be started quickly with the Ctrl+Shift+X shortcut.  Will this suffice instead of starting it automatically?
