### ISSUE TITLE
N900: Device Does Not Boot After Shutdown From System Menu Until Battery Removed

### ISSUE THREAD

**Issue by sicelo** [maemo-leste/bugtracker#125]
When using the system menu to shut the system down, it shuts down completely (which is the desired action - opposite of #85 ). However, the device will not boot afterwards until the battery is first removed.

**Comment by pavelmachek** [comment]
I tried again, held power button again, and now it shut down and will not come up. So it is possible that it works after "sudo poweroff" but does not work with other methods...?

**Comment by pavelmachek** [comment]
Strange. sudo poweroff (while connected by USB to computer) powers it off and I can use power button to wake it up.

**Comment by MerlijnWajer** [comment]
I've debugged this with @freemangordon. It looks like dsme calls 'telinit 5', which tries to bring the system to actdead (actually reboot and then actdead) runlevel, which is not actually poweroff. This likely explains why the system is stuck in a weird state. Proper solution will be to add support for actdead runlevel. I am personally inclined to make it call 'telinit 0' for now, and then add an issue for supporting actdead, because I think this will take quite some time.

**Comment by MerlijnWajer** [comment]
https://github.com/maemo-leste/dsme/blob/master/modules/runlevel.h#L34

**Comment by spinal84** [comment]
Just a note: the purpose of actdead mode is to have battery charging and alarm working.
Some explanation below.

By default bq24150a (n900 charging module) is programmed to limit current to 0.1A and voltage to 3.54V.
What it means is that your battery will be charged with very small current and only if it is almost dead.
When the kernel is boot, it initializes bq24150a to charge the battery to 4.2V with 0.95A current limit.

That's the point why Nokia did that actdead mode for n900 and possibly other devices.

**Comment by spinal84** [comment]
I don't think we have to implement actdead mode to fix the issue. As far as I can see, shutdown menu item doesn't actually shut down the device. What it does is sending shutdown command to dsme, which just turn the display off. And that's all. Your system is still running.

You can check this easily. All you need is just make network on before turning the device off from the menu.
Now check that you still can do ssh to the device. That's why you have to remove the battery.

P.S. One more interesting thing: if you make "shut down" from the menu and your charger is not connected to n900, the battery will be drained in several hours to almost dead state.

What should be done: integrate DSME with openrc or whatever init system is used on your device. It's just a matter of adding a single line to DSME source:
system("/sbin/poweroff");

**Comment by MerlijnWajer** [comment]
I think the menu should invoke shutdown via dsme - it should do more than just off the screen. I do agree that we should just try to get this fixed soon and implement actdead later.

**Comment by MerlijnWajer** [comment]
@spinal84 - I think, if we make a new issue for adding actdead support back (at some point), we can merge your PR to disable actdead for now and close this issue.

**Comment by MerlijnWajer** [comment]
I don't know why this got auto closed.

**Comment by MerlijnWajer** [comment]
Anyway, with the latest kernel and dsme from leste devel repo, I can power off the n900 using the menu. And power it on, too. Without removing the battery.

**Comment by MerlijnWajer** [comment]
@spinal84 or @sicelo - please confirm and then we can close this issue.
