### ISSUE TITLE
Fixup libicd-network-ipv4 scripts

### ISSUE THREAD

**Issue by MerlijnWajer** [maemo-leste/bugtracker#128]
They do not seem to work in dash.

**Comment by MerlijnWajer** [comment]
This is fixed.

**Comment by dderby** [comment]
@MerlijnWajer, `50_ipv4_network_setup` now depends on bash.  Bash is not the default shell (/bin/sh) in Devuan, nor Fremantle.  I'd rather fix it to be POSIX shell compatible as I think Bash should be optional rather than a dependency.  I think I've seen where it's broken and I'd like submit a fix but I don't have any details on how to reproduce the problem you were seeing.  If you can tell me how to reproduce it, I'll test my fix.  Otherwise I can submit a PR for you to test and you can tell me if works.

**Comment by MerlijnWajer** [comment]
The easiest way to test your fix is to launch udhcpc with that script. But perhaps a better way would be to set up a n900 with icd2 and my wireless plugin, and then connect to a wireless network.

What fix do you have in mind? I can test it relatively quickly if you think it's simple.

**Comment by dderby** [comment]
I won't be able to test it until tonight so it might be better if you test it.  
 
I was going just to remove a couple of _bashisms_:

https://github.com/maemo-leste/libicd-network-ipv4/blob/006d11e32494adf570550f4ea2d5a3d4d05dfd12/etc/50_ipv4_network_setup#L49

That one I'd expect to break dash as `==` is not a valid operator.  It should be `=`.

https://github.com/maemo-leste/libicd-network-ipv4/blob/006d11e32494adf570550f4ea2d5a3d4d05dfd12/etc/50_ipv4_network_setup#L93

This one is an XSI extension rather than a bashism but it probably should be replaced as follows if we want it to be POSIX complaint:

```if [ "$1" = bound]] || [ "$1" = renew ]; then```

More info on the POSIX spec here:
http://pubs.opengroup.org/onlinepubs/9699919799/utilities/test.html

**Comment by MerlijnWajer** [comment]
Fixed in 0.25.3
