### ISSUE TITLE
network applet doesn't work as expected

### ISSUE THREAD

**Issue by spinal84** [maemo-leste/bugtracker#224]
Steps to reproduce:
1) Unpack fresh Maemo Leste n900 image to microsd card.
2) Boot the phone with microsd inserted.
3) After the system booted go to hildon menu and tap "Internet connection" as soon as possible.

What happens? Nothing.
What should happen? Wifi connections list should appear.

**Comment by Suppresed** [comment]
This also happens after `apt upgrade` on the 20190225 release

**Comment by MerlijnWajer** [comment]
This is probably fixed by having `icd2` start earlier on. Before hildon-desktop at least, perhaps?

**Comment by MerlijnWajer** [comment]
@spinal84 - would you mind trying that out?

**Comment by MerlijnWajer** [comment]
Also, conndlgs should be running too.

**Comment by sicelo** [comment]
I also observed issues possibly related to this one:

1. When connected to a network for a while, and you move out of range, the icon on the status menu starts blinking indefinitely, and attempting to click the connection chooser on the status menu in order to disconnect, the connection chooser dialog does not show up. This happens even when icd2 is running. In my testing, the only way to stop the icon blinking was to reboot.
Then I set wifi connection to "Always Ask" which led to:
2. With icd2 running, and connection mode set to "Always Ask", it was no longer possible for me to connect to a network, exactly same situation as post #1. 

Previous post says to ensure conndlgs is running. I confirmed that `connui-conndlgs` is installed, but `dpkg -L` does not show any service files included with it. Or should we have the package dpkg marks as conflicting, `osso-connectivity-ui-conndlgs` ?

**Comment by sicelo** [comment]
with updated `connui-conndlgs`, this problem is solved for me.

**Comment by MerlijnWajer** [comment]
There are definitely still issues connecting to APs if you 'wait' a long time in the dialog, but if the original report was about the dialogs not appearing, then that's fixed. @spinal84 wrote 'as soon as possible', so I thought this was about icd2 starting later than h-d, perhaps.

**Comment by MerlijnWajer** [comment]
Can we close this then?

**Comment by IMbackK** [comment]
this issue is really a more general one where daemons are not ready when h-d shows up
closing here for now
