### ISSUE TITLE
Import DrNokSnes

### ISSUE THREAD

**Issue by MerlijnWajer** [maemo-leste/bugtracker#331]
See:

1. https://github.com/maemo-leste/bugtracker/issues/238
2. https://github.com/android-808/drnoksnes
3. https://github.com/android-808/drnoksnes-extrasrepo

I don't know on top of my head which repo is most up to date.

**Comment by clort81** [comment]
Will also check out differences to the openpandora snes emus.

I have some experience with them, but forgot most of it.

**Comment by MerlijnWajer** [comment]
@android-808 reported to get something working, but I've never gotten things to work beyond the launcher.

**Comment by clort81** [comment]
![leste-dns-performance](https://user-images.githubusercontent.com/51511737/78918816-44b85880-7a91-11ea-9939-3b21da9393a7.png)

I'll note here that 24bit hildon animation actor backend manages to also hit 50fps in the test, but there's apparently a 16bpp->24bpp conversion missing in the rendering.  

The Makefile doesn't complete but it can be built by hand.

The GUI doesn't build - some hildon knowledge is needed to fix.

**Comment by MerlijnWajer** [comment]
I got the GUI to build before, what error are you running into?

**Comment by MerlijnWajer** [comment]
And the Makefile also worked for me, but I got no output on the screen. Did you change anything in the emulator source code itself?

**Comment by MerlijnWajer** [comment]
And most importantly, what repo did you use?

**Comment by android-808** [comment]
I think https://github.com/android-808/drnoksnes was the latest.  I think I started to work on a amd64 version with a little success and then found the extras/garage repo that included a few Harmattan updates, including some amd64 work.  So I rebased everything against that.

I think the render code was very specific to the Maemo devices, hence the lack of 16>24bpp conversion in some modes.

**Comment by clort81** [comment]
Source repo was [android-808/drnoksnes](https://github.com/android-808/drnoksnes)

My repo is at [clort81/drnoksnesleste](https://github.com/clort81/drnoksnesleste)  Contains minor changes.

my build error on the gui is:
```
plugin.c: In function ‘get_parent_window’:
plugin.c:125:22: error: request for member ‘ui’ in something not a structure or union
  return GTK_WINDOW(gs.ui->hildon_appview);
```

**Comment by clort81** [comment]
> I think https://github.com/android-808/drnoksnes was the latest. I think I started to work on a amd64 version with a little success and then found the extras/garage repo that included a few Harmattan updates, including some amd64 work. So I rebased everything against that.
> 
> I think the render code was very specific to the Maemo devices, hence the lack of 16>24bpp conversion in some modes.

Does the android-808/drnoksnes build for you on leste / droid4?  on mine it fails bizzarrely.

**Comment by MerlijnWajer** [comment]
Builds fine for me with dpkg-buildpackage on amd64. Will try on droid in a bit.

**Comment by MerlijnWajer** [comment]
@android-808 - what setting did you use on amd64 to make it work reliable? I'm having trouble getting to work reliably.

**Comment by android-808** [comment]
Off hand I can't remember exactly. I didn't enable scaling from what I remember. I tried to keep the render as simple as possible whilst trying to get the UI working.

We had the issue with the file browser not showing correctly so I hard coded a ROM filename as part of the start up as file browser worked after setting a filename. Other than that, launcher UI was fine.  Switching from ROM to launcher wasn't correct, it showed task switcher.  Both of these I think are/were external issues.

Save/Restore functionality untested. As with other gio/gvfs adaptions like marble, chess I'm no expert so there could be issues.

**Comment by MerlijnWajer** [comment]
The file browser should be fixed. What happens to me a lot is that drnoksnes crashes (for reasons I have to debug), and then the launcher is in a buggy state.

I think it works for a bit for when I disable 'accurate graphics', disable all scaling and speedhacks. But then later on it still segfaulted in some pixel drawing. Did you change the bits per pixel of your X?

**Comment by android-808** [comment]
That sounds about right. I think you can turn one of them on but it'll only work some of the time. I didn't touch bpp.

I may take another look at the code to see what emulator is in use, find Maemo bits and then see if I can integrate them with a newer version. Ideally I would like an osso-games-startup based launcher for libretro but that's beyond me at the moment.

**Comment by MerlijnWajer** [comment]
Any update on this? Would be cool to have. ;-)

**Comment by android-808** [comment]
I'll be honest, I haven't touched the code itself due to other issues.  The only project to have seen any work is experimenting with the Pi to learn about some network services, reverse proxies etc.

I did find a few things that might be of interest.  There's a commit about removing hildon-games-wrapper that was needed to add Zeemote support (https://github.com/android-808/drnoksnes/commit/346d0cc83e6586a8802e24b61577b83c02a88719) which may or may not have something to do with the switching between game and menu showing the task switcher instead.

Libretro-snes9x2002 core features some of the asm code used by Notaz in DrNokSnes.  It has also seen a number of commits over the years so it could be worth seeing if any of it could be integrated into the app.  Some of the copyright dates in our app are past 2002 but I have not idea what versions ours of PocketSnes/Snes9x etc ours is derived from.  Of all the Snes9x related cores for libretro, its the only one to make use of assembly in source files for ARM.  Alternatively could we just build the libretro core and then rework existing GUI as a front end.

I've been messing around with the VMs today trying to get myself organized a bit (VirtualBox/sshfs/NAT-Networks etc).  Might try to have a look over the next few days to see if I can get it building in current state and see what happens.

**Comment by android-808** [comment]
Current version in my repo needs control.m4 updating as libxsp-dev is not used on Maemo 5 according to the [source code](https://github.com/android-808/drnoksnes/blob/c7d1041ea7497aaf579139caa7ff993b7df535dd/debian/rules#L81).

I had to run debian/rules debian/control to generate the control file before dpkg-buildpackage would work.

GUI is built but icon is missing from menu until reboot.

With GUI on amd64 VirtualBox image, only no scaling, accurate rendering disable loads correctly.  Default setting crashes after a second or so with corrupt colours.  Other options have correct colours but still crash.

Input isn't working at the moment with stock build using only packages in repo plus my sdlhaa.

**Comment by android-808** [comment]
As posted over in my issue tracker, I'm doing an experiment to work out the differences between DrNokSnes and libretro-snes9x2002.  They have all older cores for Snes9x reformatted and converted to C so a straight diff is out of the question.  The sources I've matched up that exist in both so far are reasonably close but I'm having to go over every stanza before merging/modifying them.

So far: 40 files changed, 10553 insertions(+), 12073 deletions(-)

**Comment by MerlijnWajer** [comment]
Great, awesome work. Regarding the input problems, I think that is a SDL problem and we have some potential fixes for that. I will take a look at that tomorrow (Sunday).

**Comment by android-808** [comment]
I'm slowly isolating the differences.  Think I'm up to something like 69 editted files, 20k+ insertions and 17K deletions but still have a way to go.

Something weird I noticed, the framerate when running a test game on the intro sequence is lower (40-60/60fps) when only testing the app, but a solid 60fps if I'm compiling the next test in the background.

**Comment by android-808** [comment]
Sort of off topic, been experimenting with other potential options as well to take a break for a bit.

Running retroarch from the repos as a test using newer snes9x 1.53 based core, it just segfaults straight away.  You also get an error regarding XDG_RUNTIME_DIR not set.  Even with a dir set it still segfaults.  Building the libretro-snes9x2002 core is fine, so I thought I'd build a basic frontend instead of the full blown retroarch and found sdlarch, which uses SDL2.

Builds fine but fails at runtime due to vertex shader version.  Modified the request GL version to 2.1, and the vertex/fragment shaders to GLSL1.2 by changing vertex shader "in" to "attribute" and "out" to "varying" and fragment shader "in" to "varying" .  Shaders compile and... segfault.  Copied file to a Debian SID VM and it works fine, but lags when moving windows around.

Are there any known issues with the GL stack/VirtualBox/SDL2?

**Comment by parazyd** [comment]
Hm, no issues really. Perhaps it's a thing that happens in hildon-desktop? I do recall some things being flaky when I ran our VM in qemu with GL enabled.

I assume your Debian Sid VM doesn't run Maemo/Hildon?

**Comment by android-808** [comment]
Sid VM running XFCE. Think both have VB Guest Additions installed. Will double check my Leste image.

**Comment by parazyd** [comment]
FWIW in Leste we also provide the same Mesa libs as Debian Sid (maybe a minor version older)

**Comment by android-808** [comment]
DrNokSnes doesn't use GL, just plain 'ol SDL1.2 so at least for this issue isn't an issue.  The libretro core uses a completely different render path for ARM compared to what we have in place.  A lot of the new os9... files are just what we have split into more managable chunks.  They have two version of the PPU code, with one specifically for ARM platforms, ppu.c, where as the other one in ppu_.c is similar to what we have.

For non-ARM platforms they are using tile.c to do a lot of the rendering which is very similar to what we have at present.  For ARM they have a new implementation that uses a number of tile16 files.  When it comes to the assembly, I haven't got a clue.

I think for DrNokSnes we just need to fix up the SDL issues so that input and fullscreen are working.  I think I may have some ideas on the colour issues based on some work earlier today.

So I've done a bit more experimenting, mixing together a few different projects, throwing out some GL and SDL2 in place of a very basic SDL1.2 based project.  Consider it a very early proof of concept/WIP.

Sound not working, no code in place.
Gameplay too fast (on Leste amd64 VM), may be because audio is disabled.
Only basic 2x software scaler, needs ScalerFactory, HAA and ARM2x scaler from DrNokSnes.
Working input but no configuration.
Need to implement #define MAEMO bits from DrNokSnes to centre the image on screen.
Needs osso.c reimplemented from DrNokSnes to allow launching from DBUS and the back arrow.
Rework the DrNokSnes UI to allow selecting file/config/core.
Save states.
Code cleanup.  It's a bit of a mess trying to hook up all the required bits as quick as possible.
Build scripts/configure/debian packaging need writing.  All I have is a basic Makefile.

After a while of sorting out stride/pitch/bpp issues:

![retro1](https://user-images.githubusercontent.com/1562358/104640519-7f929100-56a0-11eb-85a8-d05e859480e0.png)

Oh, and one libretro-fetch.sh corename and libretrobuild.sh corename later means you can do this...

![retro2](https://user-images.githubusercontent.com/1562358/104640522-80c3be00-56a0-11eb-9cd7-9893d5a7c354.png)

**Comment by MerlijnWajer** [comment]
That's awesome. Sorry i didn't get to the input and fullscreen parts yet, something came up, hope to do this ASAP though. This is real encouraging.

**Comment by android-808** [comment]
Another DrNokSnes minor issue.

Open the app and click restart, the dialog displays correctly. Confirm, enter the game and then click back.  Clicking restart again displays the dialog displays but with almost zero padding around the edges.  This is under Virtualbox.  Not major so not worried about it at the moment.

I now have a frame rate limit in place on the test app above.  Sound is also working but is a bit glitchy.

**Comment by MerlijnWajer** [comment]
@android-808 - in the -devel repositories there should be fixes for fullscreen and input in libsdl, so that might help propel this forward?

**Comment by MerlijnWajer** [comment]
Is the code to "MaemoArch" available somewhere, knowing it's work in progress?

**Comment by android-808** [comment]
MaemoArch isn't in a repo at the moment. Haven't worked on it for a while again due to other issues. What there is is a messy combination of 3 projects (DrNokSnes UI files, sdlarch derived base, some retroarch bits), some of which aren't even built, just waiting to be adapted.  One issue I've had is accurate frame time/sync. SDL1.2 doesn't support vsync so keeping audio buffer in sync is a pain. First time I've dealt with audio so not surprising.

I did try SDL2 with OpenGL before adapting to SDL1.2 but it just failed to start straight away. Same launching repo (Devuan?) versions of Retroarch. Need to test now fixes are in devel for full screen.

DrNokSnes needs a bit of work on screen resolution fixes and colour conversion. Might be ok on device but is still need up on amd64 virtualbox.

On 23 May 2021 09:32, Merlijn Wajer ***@***.***> wrote:

Is the code to "MaemoArch" available somewhere, knowing it's work in progress?

**Comment by MerlijnWajer** [comment]
Ok, so you think it's still worth it trying to get DrNokSnes going? I figured maybe MaemoArch would/could replace it entirely.

**Comment by IMbackK** [comment]
dont rely on vsync on mameo devices, the mapphones dont have a vsync like you would expect.

**Comment by MerlijnWajer** [comment]
BTW: SDL2 should work OK now, as far as I know, so if it crashes in SDL2, we'd like to hear for sure.

**Comment by android-808** [comment]
I'd get DrNokSnes and PicoDrive (not sure if I uploaded that from memory) polished first. Get something usable out there users are familiar with.

MaemoArch is a very simple test app at the moment. Settings, scalers, input config, save states, core loading, core options etc to name but a few. Cores need packaging. Devuan has some but not necessarily the lightweight version of each.

On 23 May 2021 11:57, Merlijn Wajer ***@***.***> wrote:

Ok, so you think it's still worth it trying to get DrNokSnes going? I figured maybe MaemoArch would/could replace it entirely.

**Comment by android-808** [comment]
> 
> 
> @android-808 - in the -devel repositories there should be fixes for fullscreen and input in libsdl, so that might help propel this forward?

I think I've done this right.  I'm using the same VirtualBox image I have been using (20210103).  Done apt update/upgrade first then added "deb https://maedevu.maemo.org/leste beowulf-devel main contrib non-free" to the end of apt sources.list before doing another apt update/upgrade.

Running drnoksnes from terminal with just romname.smc as param (no fullscreen), game input isn't working (might need config change) but I can close the window. Running with -f I can't interact with anything.  Using VirtualBox to send ACPI shutdown message I can get the power button menu but can't click anything.

Running via the front end app.  Accurate Graphics exits straight away if enabled. No zoom works fine (audio/video/input/back button).  Scale to fit works but video is not centered and corrupt (colour conversion/stride issue possibly due to VB resolution).  Fill entire screen still instantly exits.

**Comment by clort81** [comment]
> > @android-808 - in the -devel repositories there should be fixes for fullscreen and input in libsdl, so that might help propel this forward?

On my version fullscreen works but requires libXsp.so.0 - this makes it omap specific.
You have made a version that goes fullscreen without it?

In fullscreen platform/sdli.cpp is active, and works with scancodes directly.   I can see keypresses but games do not respond.f

**Comment by android-808** [comment]
Fremantle from what I can make out didn't actually use libXsp in the end though, that was there for earlier OS versions: https://github.com/android-808/drnoksnes/blob/c7d1041ea7497aaf579139caa7ff993b7df535dd/debian/rules#L80

**Comment by clort81** [comment]
Ok pulling together what i have, this repo should be cloneable, **dpkg-buildpackageable**

And you should get a **launchable drnoksnes frontend**, with **regular maemo menu icon/launcher**

VIdeo defaults to fullscreen 2x with software scaling.  More notes in teh README_leste.txt
[](https://github.com/clort81/drnoksnesleste)

**Comment by MerlijnWajer** [comment]
@clort81 - The repository you linked doesn't build on amd64 - I assume you mostly tested it on the D4?

**Comment by MerlijnWajer** [comment]
I modified the Makefile a bit to build for amd64, but it seems to still crash in Donkey Kong Country 2, but maybe this is specific to amd64.

**Comment by clort81** [comment]
I never built on AMD64, sorry.  As I'm back in 16bpp mode, i have working DKC2 in modes: Scale to Fit, 2x zoom and "Fill the entier screen"

**Comment by MerlijnWajer** [comment]
I'd still like to get this going some time soon, but I really forget what the status of all of this is, we have a better/faster 2D/3D now, so maybe we can do without some of the speedups.

**Comment by IMbackK** [comment]
note that retroarch works on mapphones and its psp style ui works quite well, not all cores work tho.

**Comment by Arno1103** [comment]
Based on android-808/drnoksnes and clort stuff, i got Drnoksnes working fine on N900 few months ago, excepting the GUI ( i replaced it by a yad clone ATM).
The key to get it working properly was the drnoksnes.conf file.: 2 examples of it were in fact available in android-808/drnoksnes/www. Based on that, i created a custom one with proper audio freq and buffer, proper sdl input and other basic settings.
The correct path is /home/user/.config/drnoksnes.conf otherwise games don't work.
The result is really good but it only works fine in 16bpp mode, which is now the default on N900.
Fullscreen works but only in 4/3 display (armx2) mode.
It works fullspeed with sound (correctly synchronised) at 50/50 fps.
It builds fine using dpkg-buildpackage.
See [https://github.com/Arno1103/drnoksnes-leste/tree/main](url)

**Comment by Arno1103** [comment]
I forgot to mention that touchscreen control and keyboard work fine, depending of settings in the .conf file.

**Comment by Arno1103** [comment]
DrNokSnes is available now in Extras repo and works fine on N900 (and also on D4 apparently).
The GUI launcher works and the emulator doesn't need any particular tweak in the config file.
So maybe this issue could be closed.
Note: it fails to build for arm64 but most emulators should work fine through RetroArch anyway.
