### ISSUE TITLE
cannot install libsdl1.2-dev

### ISSUE THREAD

**Issue by buzztiaan** [maemo-leste/bugtracker#345]
Droid4 , fully updated beowulf 

Trying to build some stuff, i needed libsdl1.2's headers, but alas ; 

```
$ sudo apt install libsdl1.2-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libsdl1.2-dev : Depends: libglu1-mesa-dev but it is not going to be installed or
                          libglu-dev
E: Unable to correct problems, you have held broken packages.

```

Forcing it through, leads me to ; 

```
The following packages will be REMOVED:
  hildon-desktop hildon-meta hildon-meta-droid4 libclutter-0.8-0 libegl1-sgx-omap4 libgles1-sgx-omap4
  libgles1-sgx-omap4-dev libgles2-sgx-omap4 libgles2-sgx-omap4-dev pvr-omap4

```

**Comment by MerlijnWajer** [comment]
@freemangordon - is this resolved?

**Comment by MerlijnWajer** [comment]
IIRC we didn't have this problem with the N900 packages, so maybe double check the deps with those.

**Comment by buzztiaan** [comment]
yesterdays/todays updates no longer made it blocking, but it -still- wants to remove hildon-desktop etc

**Comment by parazyd** [comment]
So a bit of update. I currently don't have time to take care of this, but here are some pointers if someone wants to tackle it:

Installation is broken on both Droid4 and N900 as far as I've tested, and it's related to the PVR packages.

* N900: https://github.com/maemo-leste/ti-omap3-sgx/tree/maemo/beowulf
* Droid4: https://github.com/maemo-leste/pvr-omap4tree/maemo/beowulf

It would be easier to figure this out on the N900 first, since there are less PVR packages to work with.

Namely, we updated Mesa to the latest Debian unstable version for all our devices, and this, as we see - broke installation of libsdl1.2

For porting Mesa, we had to also build libdrm and libglvnd. You can find which packages they now provide in their `debian/control` files:

* https://github.com/maemo-leste/mesa/blob/maemo/beowulf/debian/control
* https://github.com/maemo-leste/libglvnd/blob/maemo/beowulf/debian/control
* https://github.com/maemo-leste/libdrm/blob/maemo/beowulf/debian/control

For anyone debugging this, the first step would be to grab the source of libsdl1.2 in Debian from https://salsa.debian.org/sdl-team/libsdl1.2 (`master` branch) and get it to build on the N900.
Also make sure you're fully updated

That would be:
```
$ apt update && apt upgrade
$ git clone https://salsa.debian.org/sdl-team/libsdl1.2
$ cd libsdl1.2
$ apt build-dep .
```

Now it will break and tell you about broken dependencies. Following this, we need to tweak the `ti-omap3-sgx` package to provide what is missing and get `apt build-dep` for libsdl1.2 working.

After getting the dependencies, one would have to try to build libsdl1.2 and if built - install it.

If all of that is completed, then the issue should be fixed.

**Comment by steward-fu** [comment]
maemo-leste runs on droid4, performance is very impressive so far ! thanks all of guys
I try to install libsdl1.2 on maemo-leste by apt but apt will remove hildon-desktop realted packages,
it means your hildon-desktop will not work after reboot (need re-flash again)
I also try to rebuild libsdl from maemo-leste github but it doesn't work (blank screen with fullscreen, must use power+vol-down to reboot)

here are the workaound to keep hildon-desktop and libsdl1.2 on your droid4 device:
$ sudo apt-get install libsdl1.2-dev -y
$ sudo apt-get install hildon-desktop hildon-meta hildon-meta-droid4 libclutter-0.8.0 libegl1-sgx-omap4
  The following packages will be REMOVED:
    libegl1
$ sudo apt-get install libsdl-mixer1.2-dev libsdl-image1.2-dev libsdl-sound1.2-dev libsdl-net1.2-dev libsdl-gfx1.2-dev -y

thanks

**Comment by buzztiaan** [comment]
there's now a better libsdl1.2-dev in maemo-devel repo , here's the steps to try that one out:

-  add -devel repo to sources.list : `deb https://maedevu.maemo.org/leste beowulf-devel main contrib non-free droid4`

-  `apt update & apt upgrade`

-  `apt purge  sgx-lib-dev pvr-omap4-dev libegl1-sgx-omap4-dev libgles1-sgx-omap4-dev libgles2-sgx-omap4-dev`

-  `apt install libsdl1.2-dev`

**Comment by MerlijnWajer** [comment]
After a little more testing, we'll move it to `beowulf` and then we can close this bug. Thanks for all the work, @parazyd !

**Comment by sicelo** [comment]
Maybe I should open separate issue for this? But `apt install libsdl2-dev` (not 1.2) fails as follows:
```
The following packages have unmet dependencies:
 libsdl2-dev : Depends: libegl1-mesa-dev
               Depends: libgles2-mesa-dev
E: Unable to correct problems, you have held broken packages.
```
The reason is:
```
root@devuan-n900:~# cat /etc/apt/preferences.d/ti-omap3-sgx 
Package: libegl1-mesa-dev libgles1-mesa-dev libgles2-mesa-dev
Pin: release *
Pin-Priority: -10
```
which comes from package `ti-omap3-sgx`

**Comment by parazyd** [comment]
@sicelo Does deleting that pin file and doing a dist-upgrade work?

**Comment by sicelo** [comment]
Yes, it worked. Thanks!
