### ISSUE TITLE
Droid 4: Make 5Ghz wifi work

### ISSUE THREAD

**Issue by MerlijnWajer** [maemo-leste/bugtracker#366]
Looks like we need to perform calibration (perhaps just once, on one device).

https://e2e.ti.com/support/wireless-connectivity/wifi/f/968/t/471332?WL1273-5GHz-band-support-for-AM335x
https://processors.wiki.ti.com/index.php/OMAP_Wireless_Connectivity_A_band_support
https://web.archive.org/web/20190810193504/https://processors.wiki.ti.com/index.php/WL12xx_NLCP_Calibration_Process
https://e2e.ti.com/support/wireless-connectivity/wifi/f/968/t/308830
https://github.com/gxk/ti-utils

**Comment by IMbackK** [comment]
I was looking into this, and will continue as soon as i have a droid4 to test with again

**Comment by IMbackK** [comment]
so i have been messing around with calibrating the wifi module here are some notes:

- the ti tool neded some makefile and script modifications to build/run on modern debian
- supposedly WL1285C is close to WL1283 but calibrating with TQS_D_1.7.ini results in unsuable wifi
- linageOS for d4 has a modifyed TQS_D_1.7.ini with everything 5GHz ripped out
- i suspect 5GHz dosent work on linageOS, maybe WL1285C is diferent somehow to WL1283 in this area? can somewone with 5GHz ap test this?
- calibrating with linageOS .ini results in working 2.4GHz wifi, but with even less range than uncallibrated.
- rmmod wl12xx, modprobe wl12xx results in the wifi interface never appering until the phone is rebooted via power off (direct reboot dosent work)
- removing and reinsterting the module is neccesary mulitple times during the cal process, making rebooting annoying and also im afraid this may mess with the process somehow.

**Comment by MerlijnWajer** [comment]
@IMbackK - can you update this with our latest findings?

**Comment by IMbackK** [comment]
Test results on my d4:
* linux stock nvs - 1-2m range
* "callibrated" nvs using  TQS_D_1.7.ini sans 5GHz parameters - 1-2m range
* Android nvs on leste - ~5m range
* Android - >30m range

Info:
* WL1285C has 2 antenna outputs. on droid 4 one (ANT1) may be directly connected to an antenna, but maybe not. The other (ANT2) is connected to a TQM679002 pa/lna [datasheet](http://www.droid-developers.org/wiki/File:Tqm679002.pdf)
* WL1285C might be using ANT1 instead of ANT2 resulting in poor range
* WL1285C may support 5Ghz, but maybe not
* TQM679002 dose not support 5Ghz bands
* TQM679002 requires an enable pin. It seams to be connected to gpio4 on the wl1285c chip, the TQS_D_1.7.ini contains several parameters relating to the pa/lna
* TXBiPFEMAutoDetect
* TXBiPFEMManufacturer
* FemVendorAndOptions
* these options are very cryptic

it seams quite clear that the Droid 4 dose in fact not support 5Ghz bands, at least at usefull range, this bug can be closed or renamed wlan range issues.

**Comment by MerlijnWajer** [comment]
Agreed, closing.
