### ISSUE TITLE
Reduce droid 4 sound output gain

### ISSUE THREAD

**Issue by IMbackK** [maemo-leste/bugtracker#377]
the gain on the output channels is to high. The speaker sounds about ready to blow at 50% volume. God help you if you plug something into the headphone jack at over 6% hifi output. the headphone amp is actually driven into saturation (look at waveform on scope) at 100% hifi output volume. Even 0% is loud.

This is  not great from a usage perspective and is likely damaging to the hardware. at the very least pluging in a low impedance headphone while the hifi output is at 100% will over current the amp, possibly blowing it depending on present hw protection.

**Comment by MerlijnWajer** [comment]
I often listen to music at 20% HiFi with the switches set to headphone and I do no notice a big degradation, nor is it insanely loud for me. Weird.

**Comment by clort81** [comment]
On my devices, headphone out is clean up to about 64% hifi vollume, beyond which i don't go because it is so loud.

The max I go with speakers is aound 64%, depending on source material.  The speakers do begin to distort significantly above 50% with full-volume sources.  

More disappointing is the inability to adjust hifi gain in small increments.  I only get four usable listening levels as options: 39, 47, 55 and 64%.

**Comment by IMbackK** [comment]
@MerlijnWajer strange i listen to music with mpd (via smplayer) at 0% hifi volume and about 50% volume in mpd and thats about upper tolerable listening volume for me. While Headphones make a difference i doubt its that mutch.

additional being able to play music though headphones, the speaker and the earpiece simultaneously may also not be great, as we then have an amp designed to drive into  a 4Ohm load driving somthing on the oder or 1Ohm load, depending on the headphones.

**Comment by clort81** [comment]
0% hifi volume gives 0% speaker volume on all my devices.

**Comment by IMbackK** [comment]
i fixed this in ucm
