### ISSUE TITLE
We need to set all the standard XDG_* envvars

### ISSUE THREAD

**Issue by IMbackK** [maemo-leste/bugtracker#426]
spec:
https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

**Comment by parazyd** [comment]
Installing consolekit (or even elogind (but we have a hard conflict on purpose here because reasons)) will fix this.

Should I look into having elogind installed, but making it not react on events? With the default configuration, elogind would just power off the device when the power key is pressed.

**Comment by MerlijnWajer** [comment]
I think that makes sense.

**Comment by IMbackK** [comment]
not sure but maybe we should just set them ourselves with a small script. Using elogind or even consolekit seams overkill for just some envvars unless they do other things we might need. in particualar we may want to avoid consolekit because it is almost unmaintained.

**Comment by parazyd** [comment]
I'd prefer having elogind instead of us having to maintain a fragile script.

I'll see if having elogind works out and update you.

**Comment by IMbackK** [comment]
what is the status of this @parazyd?

**Comment by parazyd** [comment]
I think it is only XDG_RUNTIME_DIR that is missing. By consolekit this gets set to `/run/user/1000`. I've changed my mind about depending on consolekit/elogind and I think we should just keep it simple and do it with leste-config.

An equivalent would be:

```
# mkdir -p /run/user/1000
# chown user:root /run/user/1000
# chmod 700 /run/user/1000
```

And since /run is tmpfs, we have to create this on every boot with something, and set the env through /etc/profile.d (we already use this directory for Qt5 env).

**Comment by parazyd** [comment]
Solved with https://github.com/maemo-leste/hildon-base/blob/master/debian/hildon-env-setup.init
