### ISSUE TITLE
MCE: event eater dosent work 

### ISSUE THREAD

**Issue by IMbackK** [maemo-leste/bugtracker#434]
The event eater (eveater) dosent work at all:

- In event eater submode event-input.c dosent set the device to active on the device_inactive_pipe see: https://github.com/maemo-leste/mce/blob/3cbee89d364eea0211fa7a37493e39a6c2b22192/event-input.c#L295 (and also the other evdev callbacks) but event-input.c still passes all events on the keypress_pipe.
- tklock.c's keypress_trigger disables the event eater whenever a power button pressed, except the condition is or'ed with is_eveater_enabled ?????WTF?????? so the eveater always gets disabled after a single keypress no matter what key it is.. see statement that starts here https://github.com/maemo-leste/mce/blob/3cbee89d364eea0211fa7a37493e39a6c2b22192/tklock.c#L1908
-  eveater dosent eat that single device_inactive=false call either because tklock.c's keypress_trigger calles synthesise_activity here https://github.com/maemo-leste/mce/blob/3cbee89d364eea0211fa7a37493e39a6c2b22192/tklock.c#L1916 this undoes the condition in event-input.c
- the eveater mode dosent seam to do anything else.

result:
the Eveater submode and all the places it its enabled/disabled is a large amount dead code, remove or figure out what its supposed to do. Assumiung a typo in the https://github.com/maemo-leste/mce/blob/3cbee89d364eea0211fa7a37493e39a6c2b22192/tklock.c#L1908 condition breaks tklock.

**Comment by freemangordon** [comment]
I think you're missing the point of event eater - in that 'mode' mce works together with systemui (tklock module) and its purpose is to consume the first TS touch or keypress when display is about to be locked (it is dimmed for a second or so) or when display is turned off because of inactivity timeout with keyboard opened. I don;t know if you can test that on d4, however, I will try on n900 and will post the result.

However, the code is not redundant at all, though it is possible there is a bug in systemui tklock module (brought in by the RE)

**Comment by IMbackK** [comment]
Did you read the code in mce? nowithstanding what event eater mode dose in systemui, the code dose nothing in mce. the code in event.c is dead beacuse tklock undose it.
