### ISSUE TITLE
Maemo Leste doesn't boot from SD on pinephone PMOS CE 3GB version

### ISSUE THREAD

**Issue by robthebold** [maemo-leste/bugtracker#448]
I believe this is particular to the 3GB CE version of the PMOS pinephone, the model that comes with the convergence package dock.

Put image on SD with Ubuntu Disks utility and Balena Etcher -- seemed successful, no errors.

Put card in phone, expected it to boot on powerup, but nothing happens, not even the red LED of nothingness that some of the other OS builds did on the 3GB version.

Tried a couple different brand new cards, flashed in multiple ways (Etcher and Disks utility). Also tried same cards with other OSs, most flashed the camera flash LED and then turned on the red LED before getting stuck. Latest UBPorts (build 78) boots up okay from SD.

**Comment by MerlijnWajer** [comment]
Thanks for the report. Potentially we need a different device tree for this model. I don't think any of the devs have this newer model yet, so we haven't been able to test that out yet.

**Comment by MerlijnWajer** [comment]
@parazyd - can you take a look?

**Comment by thunderysteak** [comment]
This issue is caused by the u-boot not being patched to support 3GB CE model
Testing a u-boot binary with the 3gb patch and applying it to the maemo leste image gets the phone to boot and function correctly
A current workaround is to source a newer uboot image and patch either the SD card or the image with DD with newer uboot
`sudo dd if=u-boot-3gb.bin of=/dev/mmcblk0 bs=1024 seek=8`

![leste](https://user-images.githubusercontent.com/16468437/93751971-e1ad1f00-fbf5-11ea-8999-b757f20378c7.jpg)

**Comment by parazyd** [comment]
@robthebold @thunderysteak 

The latest Pinephone image should have the latest u-boot available. If not, then this Sunday it'll be built.
If not, u-boot can be retrieved from https://maedevu.maemo.org/leste/pool/pinephone/p/pine64-uboot/pine64-uboot_0.7%2B2m7.1_all.deb

**Comment by parazyd** [comment]
Please reopen if you still have issues with latest images.

**Comment by robthebold** [comment]
I finally got an extra SD card to verify this, and yes, it boots up fine on the 3GB version PinePhone now.
Thanks!
