### ISSUE TITLE
Port + import hamsterfiler

### ISSUE THREAD

**Issue by MerlijnWajer** [maemo-leste/bugtracker#499]
http://maemo.org/packages/view/hamsterfiler/

**Comment by android-808** [comment]
Attempted to build as is just to see what message get thrown to start with for anyone taking it on:
- Rules needs updating as it specifies qt4 qmake
- Control file is missing qt5 depends (libqt5maemo5 and libqt5x11extras5)
- There's a gnome-vfs-mime-utils include that needs removing/replacing.
- There's a kinetic scroller include that needs replacing.
- Build will then fail on main.cpp:19 due to a missing definiton, fixed with https://doc.qt.io/qt-5/signalsandslots.html#using-qt-with-3rd-party-signals-and-slots but all signal and slot mentions in headers need replacing as documented on the link.
- Main.cpp will now build and your porting fun can begin...

**Comment by MerlijnWajer** [comment]
It should be pretty simple to do this now actually. I have kinetic (QScroller) replacements in all the Qt5 ports I did for leste (Dorian, Qalendar, gpsrecorder just to name a few).

In general, they commit history of those projects should have solutions to most of the problems you'll encounter.

**Comment by freemangordon** [comment]
On a side note - I'll have a look at default file manager someday

**Comment by sanderfoobar** [comment]
https://github.com/sanderfoobar/hamsterfiler
https://github.com/maemo-leste-extras/bugtracker/issues/26
