### ISSUE TITLE
icd2/busybox-udhcpc: Respect DNS (resolv.conf) from DHCP upon connection

### ISSUE THREAD

**Issue by parazyd** [maemo-leste/bugtracker#507]
We currently always stick with the default image's nameservers, but we should take what DHCP gives us.

**Comment by sicelo** [comment]
it is not an issue with `udhcpc`, which does correctly set the DNS in `/var/run/resolv.conf.<iface>`. What we are missing is something to 'connect' DNS servers to the standard `/etc/resolv.conf`

**Fix 1:**
Fremantle used `dnsmasq` withthe following configuration. If we follow its setup, we would need `/etc/dnsmasq.d/00_leste_dns_config` with the following (adapted from Fremantle's `/etc/dnsmasq.conf`):
```
domain-needed
bogus-priv
resolv-file=/var/run/resolv.conf
resolv-file=/var/run/resolv.conf.wlan0
resolv-file=/var/run/resolv.conf.ppp0
resolv-file=/var/run/resolv.conf.lo
resolv-file=/var/run/resolv.conf.gprs
```

**Fix 2:**
Enter the dns values from DHCP straight into `/etc/resolv.conf`. This will need the following patch:
```
diff --git a/etc/50_ipv4_network_setup b/etc/50_ipv4_network_setup
index 5af759d..5a68b60 100755
--- a/etc/50_ipv4_network_setup
+++ b/etc/50_ipv4_network_setup
@@ -1,7 +1,7 @@
 #!/bin/sh
 # udhcpc script to use with ICD
 
-RESOLV_CONF="/var/run/resolv.conf.$interface"
+RESOLV_CONF="/etc/resolv.conf"
 LEASE_PARAMS=/var/run/dhcp-params.conf
 
 case "$1" in
```

I have tested both approaches on the Droid 4, and they resolve this issue, at least for WiFi. None of them work for 3G yet, but that's due to the fact that libicd-network-ofono is still WIP - and currently (wrongly?) saves the DNS in gconf.

**Comment by parazyd** [comment]
I wanted to set up dnsmasq, as this is what was happening on Fremantle, and we also want dnsmasq anyway so we can have DHCP on usbnet and WiFi hotspots.

**Comment by parazyd** [comment]
I implemented this in -devel in https://github.com/maemo-leste/libicd-network-ipv4 by adding the dnsmasq config and dependency on dnsmasq.

Will test for a bit and see what to do with gprs, then I'm going to move it to main.

**Comment by buzztiaan** [comment]
my fix for cellular for now is just overwriting resolv.conf with a knowngood dns server

**Comment by MerlijnWajer** [comment]
Pretty sure I solved this particular problem a while ago, let's file a separate issue for the gprs stuff
