### ISSUE TITLE
desktop-cmd-exec: does not execute commands that do not return values

### ISSUE THREAD

**Issue by clort81** [maemo-leste/bugtracker#558]
hi parazyd :)

I noticed d-c-e can't run a script that simply does echo "something" > something_else.

If this isn't a 'just me problem', It would be good to fix.

cheers!

**Comment by sicelo** [comment]
DCEW was running the command successfully, even if it did not return any value. It just 'wrongly' displayed "Invalid Command," although that was fitting, in view of the purpose of the widget as stated in its description - "Presents the updated result of a custom shell command in your desktop."

Anyway, I've now made some adjustments to the widget:
 - if a command that has no output is run, it will now display "Success - no output"
 - if a command has errors, and thus fails to run, it will show "Invalid Command"

Additionally, since `/home/user/.desktop_cmd_exec` caches the commands to be run, including the ones shipped with the package, you may want to delete that file (or back it up), since I also took the opportunity to remove obsolete Fremantle commands from the widget.

When the package has been built and updated in the repos, note that due to #368, you will have to reboot the device after updating.

In passing, maybe DCEW bugs/issues should go to https://github.com/maemo-leste-extras/desktop-cmd-exec/issues
