### ISSUE TITLE
N900: ssh -X to maemo loads keyboard map on PC

### ISSUE THREAD

**Issue by pavelmachek** [maemo-leste/bugtracker#60]
...which results in unusable PC where many characters can not be typed. For example numbers. Nice trap.

**Comment by parazyd** [comment]
You can temporarily disable it in `/etc/profile.d/nokia-n900-keymap.sh`. Let us know if you know of a better way to load these keymaps.

**Comment by MerlijnWajer** [comment]
@parazyd - shall we see if can fix this soon? It does seem to be rather annoying, and the fix shouldn't be too hard, I think.

**Comment by MerlijnWajer** [comment]
How would I test this? I don't think I follow your question. If you ask if loadkeys() affects my host machine, then that's a no.

**Comment by dderby** [comment]
This should be configured in `/etc/default/keyboard` rather than create another `xorg.conf.d` file.  Example:
https://github.com/dderby/debian900/blob/master/install_debian.sh#L264-L267

**Comment by parazyd** [comment]
@dderby It seems to me that is for the console keyboard layout. This issue is about the Xorg one.

**Comment by dderby** [comment]
@parazyd, I believe it's for both console and Xorg keyboard configuration (sorry, the comment in my script is misleading).  It's been a while since I've touched this so I may be mistaken but I am fairly certain that I did not need to configure the X11 keyboard in xorg.conf(.d).  The keyboard(5) manual states:
> In Debian systems the default keyboard layout is described in /etc/default/keyboard and it is shared between X and the console.

The variables that start with XKB should configure X keyboard extensions.  Further reading of that manual suggests that I may not have had to set the KMAP variable as I had been doing.  I'll see I get a chance to test this tonight and come up with what I think the correct keyboard configuration should be.

**Comment by dderby** [comment]
The `setupcon` command requires the `console-setup` package which is not installed by default.  @parazyd, can we place this in `extra_pacakges` in `image-builder/leste.config` or do you have a better suggestion?

**Comment by dderby** [comment]
The `setupcon` command is called automatically by a postinst script when `console-setup` is installed.  So we just need to install this package ensuring that `/etc/default/keyboard` from https://github.com/parazyd/arm-sdk/pull/2 is already overlayed at the time the package installed and we'll have a nice, clean configuration of both the X11 and console keymaps.

**Comment by dderby** [comment]
We can do even better than this.  This can be set up automatically in the package config.  I'm going to create a patch to detect RX-51 hardware and set XKBMODEL.  I'll submit it upstream and hopefully it will land in buster/beowolf.

**Comment by dderby** [comment]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=893814

**Comment by parazyd** [comment]
@dderby We will still have to backport it for Ascii. Should I add console-setup to the default package array then?
