### ISSUE TITLE
charge-mode: boot when battery capacity <10%

### ISSUE THREAD

**Issue by sicelo** [maemo-leste/bugtracker#686]
`charge-mode` has a hardcoded 10% battery level before one is able to boot to default runlevel. However, there is no indication to the user that this is the case. so user will hit the (fragile?) power key a number of times before eventually giving up

suggestions:

1. allow user to power on device anytime, since it is already on a charger and not really likely to consume that much more power
2. provide a (visual?) notification that it is not possible to boot to system until 10% has been reached

I would recommend option 1

**Comment by freemangordon** [comment]
>     1. allow user to power on device anytime, since it is already on a charger and not really likely to consume that much more power
> 
>     2. provide a (visual?) notification that it is not possible to boot to system until 10% has been reached

3. Do not enter charge-mode at all, if connected to wall charger

**Comment by IMbackK** [comment]
1. wold be good but is currently not possible due to kernel limitations
i strongly disagree that 3 is ok, if the device is booted with usb pluged in it shal enter charge mode unless power is pressed

**Comment by spinal84** [comment]
AFAIK the sense of charge mode is to protect fully discharged battery from capacity loss and overheat when charging with high currents. This is because Li-ion drastically increases its internal resistance when it's at near discharged state. Using the device while the battery is almost discharged with charger connected will also increase the battery temperature. Which is very bad for Lithium chemistry - it will degrade much faster.
