### ISSUE TITLE
Provide some prebuilt kernels (and optionally a git repo with changes if any)

### ISSUE THREAD

**Issue by MerlijnWajer** [maemo-leste/bugtracker#7]
For supported devices this would be useful

EDIT: (parazyd)
Package our kernels into deb packages eventually, making us able to ship kernel updates easily. They should each go into their respective repo component (n900/droid4/...) when built.

**Comment by parazyd** [comment]
What is the status of this ticket? Currently all the sources are handled in arm-sdk.

If we actually want to provide prebuilt kernels, I think the best way is to build them as deb packages.

**Comment by MerlijnWajer** [comment]
Maybe change the ticket desc to provide kernel packages per device type; as debian packages, so that people can also actually update to get new kernels at some point.

We can leave this open. But we should probably fix it for the alpha or beta release.

**Comment by dderby** [comment]
I don't know if you know this already but deb packaging (and rpm) comes free with the kernel build scripts.  Just build it with the _deb-pkg_ make target and it will automatically build the deb files for you.  For the N900, I've been patching the _postinst_ script so that it automatically appends the device tree to the zImage and also builds the U-Boot kernel image: https://github.com/dderby/debian900/blob/master/build_kernel.sh#L68

**Comment by MerlijnWajer** [comment]
Let's close this and make a separate issue for kernel debs.
