### ISSUE TITLE
Droid4: hildon-desktop (or something else?) does not register touchscreen clicks

### ISSUE THREAD

**Issue by MerlijnWajer** [maemo-leste/bugtracker#78]
Certain parts of the desktop do not work. For example, the terminal menu doesn't show. The same is true for the desktop customisation gear that appears when you click on the desktop.

I think the same problem exists on the A33 tablet?

**Comment by dderby** [comment]
I confirm that I've seen the same thing on the Droid 4 although I'd like to add that I have actually got the terminal menu to appear once or twice.  I'm not sure what it depends on.

**Comment by dderby** [comment]
I found that when I press on the X Terminal icon, sometimes it tries to open the tana_ap_user_guide instead.  Could it be that the touchscreen incorrectly calibrated?

**Comment by dderby** [comment]
I recalibrated the touchscreen and it fixed my issue when pressing the  X Terminal icon but it did not fix the issue with the X Terminal menu.

Here's the config I'm now using on the Droid 4 if you're interested:
```
Section "InputClass"
        Identifier      "calibration"
        MatchProduct    "Atmel maXTouch Touchscreen"
        Option  "Calibration"   "-2 917 1045 -20"
        Option  "SwapAxes"      "1"
EndSection
```
It's not perfect (it's quite difficult to calibrate a capacitive touchscreen), but it might be useful to someone.

**Comment by MerlijnWajer** [comment]
OK, well, if this works, let's merge this and close the issue. I can test it tonight.

Thanks.

See #41 as well - I guess?

**Comment by dderby** [comment]
I don't we're ready to close it as it did not fix the issue with the osso-xterm menu click which I mentioned above.

**Comment by MerlijnWajer** [comment]
Ah, I misread - was early. OK, so you are having the same problem as I had.

**Comment by freemangordon** [comment]
for the gear:

( 8,18,10) freemangordon: Wizzup: I doubt it is because it is capacitive, rather it is because gtk generate "touch" instead if "click" events
( 8,48,28) freemangordon: Wizzup: look at https://github.com/maemo-leste/hildon-desktop/commit/1d71c904a5bb219094f6ebb487c49f877af04813
( 9,05,33) freemangordon: Wizzup: I guess https://github.com/maemo-leste/hildon-desktop/blob/94bc0ad868cc9af9afcb7ad83b90918dee26f104/src/home/hd-home.c#L1373 is where "touch-event" handling should be added
( 9,11,19) freemangordon: similar to https://github.com/maemo-leste/hildon-desktop/blob/94bc0ad868cc9af9afcb7ad83b90918dee26f104/src/home/hd-title-bar.c#L1510
( 9,12,34) freemangordon: with only CLUTTER_TOUCH_END processed, generating a synthetic call to hd_home_edit_button_clicked

there should be similar fix needed for the osso-xterm, but I am not sure if h-d should be fixed or the application itself

**Comment by MerlijnWajer** [comment]
Thanks, seems simple enough. I'll get it done and also check other parts of h-d and xterm.

**Comment by MerlijnWajer** [comment]
I've committed various touch fixes for hildon-desktop, but this particular one is not fixed yet.

With these commits, hildon-desktops allows pressing the edit button, allows pressing applets and allows moving and deleting applets:

https://github.com/maemo-leste/hildon-desktop/commit/180c5069e1a3ccc0e3a31c86a997ac1bdbc82d22
https://github.com/maemo-leste/hildon-desktop/commit/bab369db0be57bca9366fe9e1a7cde0c40fffbb5

Using gdb I've found that `hildon_window_event_filter` in hildon.git is not triggered for touch events.

**Comment by MerlijnWajer** [comment]
This commit fixes the problem for me. https://github.com/maemo-leste/libmatchbox2/commit/5c18fb8583f14feab404b45853149adb502f2fcc

**Comment by MerlijnWajer** [comment]
@freemangordon Can you review the above commits? The last one (to libmatchbox2) is the tricky one.

**Comment by MerlijnWajer** [comment]
I think my commits to h-d above need some more fixes, so let's not build a new release from this yet.
